server:
  public:
    bindAddress: "127.0.0.1:6648"
    auth:
      provider: "oidc"
      providerParams: "{}"
#    tls:
#      certFile: ""
#      keyFile: ""
#      minVersion: 0
#      maxVersion: 0
#      trustedCaFile: ""
#      insecureSkipVerify: false
#      clientAuth: false
  internal:
    bindAddress: "127.0.0.1:6649"
#    tls:
#      certFile: ""
#      keyFile: ""
#      minVersion: 0
#      maxVersion: 0
#      trustedCaFile: ""
#      insecureSkipVerify: false
#      clientAuth: false
replication:
#  tls:
#    certFile: ""
#    keyFile: ""
#    minVersion: 0
#    maxVersion: 0
#    trustedCaFile: ""
#    insecureSkipVerify: false
#    serverName: ""
storage:
  wal:
    dir: "./data/wal"
    sync: true
    retention: "1h"
  database:
    dir: "./data/db"
    readCache: "100MiB"
  notification:
    retention: "1h"
observability:
  metric:
    bindAddress: "127.0.0.1:8080"
  log:
    level: INFO
    format: TEXT